spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?serverTimezone=UTC
    username: root
    password: Yang19990416!!
mybatis:
  type-aliases-package:com.yh.pojo